Initial implementation
CoreumFoundation/iso20022-client pull request #1
Opened 2024-06-19 08:20 UTC by masihyeganeh

2024-06-28 10:32 UTC, miladz68 requested changes
> Reviewed 65 of 73 files at r1, 27 of 28 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1)* status: all files reviewed, 37 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`go.work` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OImLzBPDDIQc7xA3j:-O0OImM-Cpz-q2tkkiSM:bgbruca) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/go.work#L1)):*
> ```
> go 1.22.1
> ```

all other repos are using go1.21, if this repo requires a higher version of go, it must download and store it some where to be used internally. 
___
*[`Makefile` line 26 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0NomcOAOfZaVKBCAnh:-O0NomcOAOfZaVKBCAni:bongx7b) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/Makefile#L26)):*
> ```Makefile
> ENTRY_FILE=iso20022/cmd/main.go
> 
> .PHONY: \
> ```

most of these commands do not exist now, some of them will not be needed in future. if you are adding them here, they must  work as intended.
___
*[`.github/workflows/ci.yml` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0Np4kKBSPSgLa9wD5I:-O0Np4kKBSPSgLa9wD5J:b-pixsvi) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/.github/workflows/ci.yml#L21)):*
> ```YAML
>         include:
>           - ci_step: "lint"
>             command: "make lint"
> ```

this CI will not work since these commands are not working. please a working CI file and make sure that github ci is configure to run it. 
I guess this is copied, but it needs to be provisioned carefully to see if it is what we need and that it works.
___
*[`.github/workflows/release.yml` line 26 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OACyxBqz3laFonqqX:-O0OACyxBqz3laFonqqY:beyua2f) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/.github/workflows/release.yml#L26)):*
> ```YAML
>         run: |
>           cd iso20022-client
>           make push-docker
> ```

I did not check, but I doubt this command works, and I am pretty sure this github action file will not work. so either fix it or commit it a separate PR as part of another task.
___
*[`iso20022/go.mod` line 3 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OA_v850vKNTbSIeFI:-O0OA_v850vKNTbSIeFJ:b-yabg33) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/iso20022/go.mod#L3)):*
> ```XML
> module github.com/CoreumFoundation/iso20022-client/iso20022
> 
> go 1.21.4
> ```

we have 2 different versions of go here and in integration tests, that should be as such. 
___
*[`iso20022/go.mod` line 5 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OAkGj2twMkekwVsJ8:-O0OAkGj2twMkekwVsJ9:b-5gdiuk) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/iso20022/go.mod#L5)):*
> ```XML
> go 1.21.4
> 
> // same replacements as in coreum
> ```

make sure you need these replacements. just blindly copying is not a good idea. 
___
*[`iso20022/addressbook/addressbook.go` line 26 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OGjbEAig9H-CagQsT:-O0OGjbEAig9H-CagQsU:bxk4q4d) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/iso20022/addressbook/addressbook.go#L26)):*
> ```Go
> func New(chainId string) *AddressBook {
> 	// TODO: replace with main branch after release
> 	repo := "https://raw.githubusercontent.com/CoreumFoundation/iso20022-addressbook/develop/%s/addressbook.json"
> ```

you are storing a string template which contains %s, do the replacement here if it is needed here. 
___
*[`iso20022/addressbook/addressbook.go` line 43 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OHADsEnckK1yyYJFN:-O0OHADsEnckK1yyYJFO:b-obas5x) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/iso20022/addressbook/addressbook.go#L43)):*
> ```Go
> // Update fetches latest entries from the repo, whether an url or a file
> func (a *AddressBook) Update(ctx context.Context) error {
> 	addr := fmt.Sprintf(a.repoAddress, a.chainId)
> ```

if it is file or url to be updated, it will probably with a fully resolved one and not a temaplate one. 
___
*[`iso20022/addressbook/addressbook.go` line 121 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OKCevBw5tVk6B7KFS:-O0OKCevBw5tVk6B7KFT:bwtm81r) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/iso20022/addressbook/addressbook.go#L121)):*
> ```Go
> 
> // ForEach loops through address book entries
> func (a *AddressBook) ForEach(f func(address Address) bool) {
> ```

this is unused.
___
*[`iso20022/addressbook/addressbook.go` line 143 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OKHo65iXOAf3ZJ4RO:-O0OKHo65iXOAf3ZJ4RP:bwtm81r) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/iso20022/addressbook/addressbook.go#L143)):*
> ```Go
> }
> 
> // LookupByAccountAddress tries to find a specific entry in the address book using bech32-encoded account address
> ```

this is unused.
___
*[`iso20022/addressbook/addressbook.go` line 26 at r3](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0T7J5D3CCqb_1dw2-T:-O0T7J5D3CCqb_1dw2-U:bg9j80d) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/73de1cd14ebcda579da26f6555e61c1c7565a9f3/iso20022/addressbook/addressbook.go#L26)):*
> ```Go
> func New(chainId string) *AddressBook {
> 	// TODO: replace with main branch after release
> 	repo := "https://raw.githubusercontent.com/CoreumFoundation/iso20022-addressbook/develop/%s/addressbook.json"
> ```

this github repo approach will make key rotation much harder down the line. I think it is better to use the smart contract to store and retrieve the address book. wdyt ?
___
*[`iso20022/addressbook/addressbook_test.go` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OKyny1rCq42JwsyMA:-O0OKyny1rCq42JwsyMB:b1b5feh) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/iso20022/addressbook/addressbook_test.go#L70)):*
> ```Go
> 		AddressLine:        []string{"j", "k"},
> 	}
> 	require.Equal(t, "AddressType=(Code=l/Proprietary=(Id=m/Issuer=n/SchemeName=o))/BuildingNumber=e/CareOf=a/CountryCode=i/Department=b/DistrictName=h/Floor=f/PostalCode=g/StreetName=d/SubDepartment=c", p.String())
> ```

What do you need this test for ?
___
*[`iso20022/addressbook/serialization.go` line 11 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OLKMx15cIscxQM2m2:-O0OLKMx15cIscxQM2m3:b-5awv43) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/iso20022/addressbook/serialization.go#L11)):*
> ```Go
> 
> // SerializeStruct produces a deterministic text representation of a struct
> func SerializeStruct(p any) string {
> ```

why do you need to serialize any struct to string ? this reflections looks a bit scary to me. 
___
*[`iso20022/addressbook/struct.go` line 3 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OLvzk2JIBC8Cd5OHm:-O0OLvzk2JIBC8Cd5OHn:bhdwyjj) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/iso20022/addressbook/struct.go#L3)):*
> ```Go
> package addressbook
> 
> type Proprietary struct {
> ```

all these types must have xml tags as well. I do [...]

2024-07-01 10:19 UTC, masihyeganeh reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1)* status: all files reviewed, 37 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`iso20022/addressbook/addressbook.go` line 143 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OKHo65iXOAf3ZJ4RO:-O0U0Mw_BRgipSGgISmj:b-bqy3ux) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/iso20022/addressbook/addressbook.go#L143)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this is unused.
</blockquote></details>

Done. It is used


<!-- Sent from Reviewable.io -->

2024-07-02 09:31 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1)* status: all files reviewed, 38 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0mm5Fn8G8ZH_cjayaA:-O0mm5FoCtpfppPNSK2w:bok52jh) (no related file):*
rename main branch to master, we have done so for every other repo.

___


<!-- Sent from Reviewable.io -->

2024-07-04 10:52 UTC, masihyeganeh reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1)* status: all files reviewed, 37 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0mm5Fn8G8ZH_cjayaA:-O0wy4jJ9HgY6m0obFyd:b-896fix) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

rename main branch to master, we have done so for every other repo.
</blockquote></details>

Done.

___
___
*[`go.work` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OImLzBPDDIQc7xA3j:-O0t4Jgd4VfZ986TUaEZ:b-896fix) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/go.work#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

all other repos are using go1.21, if this repo requires a higher version of go, it must download and store it some where to be used internally.
</blockquote></details>

Done.
___
*[`Makefile` line 26 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0NomcOAOfZaVKBCAnh:-O0t6orR-wdNFmQpX_4O:b-896fix) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/Makefile#L26)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

most of these commands do not exist now, some of them will not be needed in future. if you are adding them here, they must  work as intended.
</blockquote></details>

Done.
___
*[`.github/workflows/ci.yml` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0Np4kKBSPSgLa9wD5I:-O0wy7B803aYHCpQjdnP:b-896fix) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/.github/workflows/ci.yml#L21)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this CI will not work since these commands are not working. please a working CI file and make sure that github ci is configure to run it. 
I guess this is copied, but it needs to be provisioned carefully to see if it is what we need and that it works.
</blockquote></details>

Done.
___
*[`.github/workflows/release.yml` line 26 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OACyxBqz3laFonqqX:-O0wy8jhBfvZ1F60JeF2:b-896fix) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/.github/workflows/release.yml#L26)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I did not check, but I doubt this command works, and I am pretty sure this github action file will not work. so either fix it or commit it a separate PR as part of another task.
</blockquote></details>

Done.
___
*[`iso20022/go.mod` line 3 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OA_v850vKNTbSIeFI:-O0wyXSr5VsCgknWxVhS:b-896fix) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/iso20022/go.mod#L3)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we have 2 different versions of go here and in integration tests, that should be as such.
</blockquote></details>

Done.
___
*[`iso20022/go.mod` line 5 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OAkGj2twMkekwVsJ8:-O0wy_-n9y8CgL4Ziw54:b-896fix) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/iso20022/go.mod#L5)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

make sure you need these replacements. just blindly copying is not a good idea.
</blockquote></details>

Done.
___
*[`iso20022/addressbook/addressbook.go` line 26 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OGjbEAig9H-CagQsT:-O0wzVP09NjoWvuKW-Sr:b-896fix) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/iso20022/addressbook/addressbook.go#L26)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you are storing a string template which contains %s, do the replacement here if it is needed here.
</blockquote></details>

Done.
___
*[`iso20022/addressbook/addressbook.go` line 43 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OHADsEnckK1yyYJFN:-O0wzaRy6Ita0IVGmsaA:b-896fix) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/iso20022/addressbook/addressbook.go#L43)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

if it is file or url to be updated, it will probably with a fully resolved one and not a temaplate one.
</blockquote></details>

Done.
___
*[`iso20022/addressbook/addressbook.go` line 121 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OKCevBw5tVk6B7KFS:-O0x2feZ0wL4iC2OHOeT:b-896fix) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/iso20022/addressbook/addressbook.go#L121)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this is unused.
</blockquote></details>

Done.
___
*[`iso20022/addressbook/addressbook.go` line 26 at r3](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0T7J5D3CCqb_1dw2-T:-O0wzXLe8MFelmDoD1kO:b-wiwr9d) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/73de1cd14ebcda579da26f6555e61c1c7565a9f3/iso20022/addressbook/addressbook.go#L26)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this github repo approach will make key rotation much harder down the line. I think it is better to use the smart contract to store and retrieve the address book. wdyt ?
</blockquote></details>

Will do in next iteration
___
*[`iso20022/addressbook/addressbook_test.go` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OKyny1rCq42JwsyMA:-O0x4IhiE2_uW_x3Ul4x:b1y5uio) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/iso20022/addressbook/addressbook_test.go#L70)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

What do you need this test for ?
</blockquote></details>

Done. Deleted
___
*[`iso20022/addressbook/serialization.go` line 11 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OLKMx15cIscxQM2m2:-O0x4Me2BzuD5D-xEdPa:b1y5uio) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/iso20022/addressbook/serialization.go#L11)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

why do you need to serialize any struct to string ? this reflections looks a bit scary to me.
</blockquote></details>

Done. Deleted
___
*[`iso20022/addressbook/struct.go` line 3 at r1](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0OLvzk2JIBC8Cd5OHm:-O0x4PUf8kxHEPgKJ14J:bkkk2z4) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/60d6d4c4320a8fe210fa372689aee416dbd1bb6d/iso20022/addressbook/struct.go#L3)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

all these types must have xml tags as well. I doubt json tags will help us here much.
</blockquote></details>

No, they don't. It's a reference datastructure
___
*[`iso20022/addressbook/struct.go` line 3 at r3](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0T5hkTCj6LgEbtnHGX:-O0x4UNnEo8aYAi2K1Nf:bgp48g) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/73de1cd14ebcda579da26f6555e61c1c7565a9f3/iso20022/addressbook/struct.go#L3)):*
<details><summary><i>P [...]

2024-07-12 04:32 UTC, masihyeganeh reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1)* status: all files reviewed, 37 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`iso20022/processes/contract_client.go` line 226 at r3](https://reviewable.io/reviews/CoreumFoundation/iso20022-client/1#-O0T3k8jEy3mKWD70Kj9:-O1_CetX9nJeo-CGTyXP:b-896fix) ([raw file](https://github.com/CoreumFoundation/iso20022-client/blob/73de1cd14ebcda579da26f6555e61c1c7565a9f3/iso20022/processes/contract_client.go#L226)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you must handle idempotency and message deduplication. put it into umbrella task. you must also consider WAL and batching.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-17 14:12 UTC, closed without merging